### ISSUE TITLE
Missing release tag

### ISSUE THREAD

**Issue by almostintuitive** [eagle-dan1349/FBSDK-RACExtensions#1]
Unfortunately without tagging the release in master, Cocoapods will fail to install the project without additional specification of branch or version.

[!] Error installing FBSDK-RACExtensions
[!] /usr/bin/git clone https://github.com/eagle-dan1349/FBSDK-RACExtensions.git /var/folders/sp/p2d9ddms3q96_rx194h0p3nr0000gn/T/d20151017-20647-19sfacs --single-branch --depth 1 --branch 0.0.2.1

Cloning into '/var/folders/sp/p2d9ddms3q96_rx194h0p3nr0000gn/T/d20151017-20647-19sfacs'...
warning: Could not find remote branch 0.0.2.1 to clone.
fatal: Remote branch 0.0.2.1 not found in upstream origin

**Comment by eagle-dan1349** [comment]
Sorry about that, strangely, tag did not get pushed. Fixed now
